### ISSUE TITLE
Segfault crash on Ubuntu 16.04 amd64 when using tlbcmd

### ISSUE THREAD

**Issue by OH1KK** [skiphansen/thelinkbox#1]
Plaform: PC with a Ubuntu 16.04 amd 64

```
git clone https://github.com/skiphansen/thelinkbox
cd thelinbox
./bootstrap.sh
./configure --enable-usb
make
cd linkbox
./tlb -d -f /etc/thelinkbox/tlb.conf
```

Then exeute tlbcmd on other shell window

```
oh1kk@oh6ruw:~/tlb/thelinkbox/tlbcmd$ ./tlbcmd link
tlbcmd Version 0.53 compiled Jan 27 2018 18:36:19
oh1kk@oh6ruw:~/tlb/thelinkbox/tlbcmd$ 
```

Command causes segfault crash in tlb

```
root@oh6ruw:/home/oh1kk/tlb/thelinkbox/linkbox# ./tlb -d -f /etc/thelinkbox/tlb.conf
thelinkbox Version 0.53 compiled Jan 27 2018 18:36:11
18:38:38 thelinkbox V 0.53 compiled Jan 27 2018 18:36:11 (pid: 4528)
18:38:38 EndPointInit: Initializing OH6RUW-Kokkola port
18:38:38 EndPointInit: called, TxKeyMethod: 5, RxCosMethod: 7 IdNoCTCSS
18:38:38 UsbInit: found USB device @ 3-2
18:38:38 UsbInit#669: usb_detach_kernel_driver_np returned -61 (No data available)
18:38:38 UsbInit: USB audio device for OH6RUW-Kokkola is /dev/dsp1
AudioInit: RxRing @ 0x20ccb60, RxRingSize: 2560
18:38:38 AudioInit: Internal sampling rate conversion for CM108 enabled
18:38:38 AudioInit: set CosPollRate to 50
18:38:38 AudioInit#2226: opening "/dev/dsp1"
18:38:38 AudioInit: Asked for a sampling rate of 48000, got 48000
18:38:38 AudioInit: sampling rate conversion from 48000 to 8000 enabled
18:38:38 Fragsize: 256, fragstotal: 5, bytes: 1280
18:38:38 EndPointInit: Setup repeat path on port OH6RUW-Kokkola.
Port OH6RUW-Kokkola: unkey
18:38:38 EndPointInit: returning 0
18:39:46 tlbcmd: "link" (0).
Segmentation fault (core dumped)
```

Debugging info
gdb --args ./linkbox/tlb -d -f /etc/thelinkbox/tlb.conf

```
root@oh6ruw:/home/oh1kk/tlb/thelinkbox/linkbox# gdb --args ./tlb -d -f /etc/thelinkbox/tlb.conf
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./tlb...done.
(gdb) run
Starting program: /home/oh1kk/tlb/thelinkbox/linkbox/tlb -d -f /etc/thelinkbox/tlb.conf
thelinkbox Version 0.53 compiled Jan 27 2018 18:36:11
18:42:13 thelinkbox V 0.53 compiled Jan 27 2018 18:36:11 (pid: 4584)
18:42:13 EndPointInit: Initializing OH6RUW-Kokkola port
18:42:13 EndPointInit: called, TxKeyMethod: 5, RxCosMethod: 7 IdNoCTCSS
18:42:14 UsbInit: found USB device @ 3-2
18:42:14 UsbInit#669: usb_detach_kernel_driver_np returned -61 (No data available)
18:42:14 UsbInit: USB audio device for OH6RUW-Kokkola is /dev/dsp1
AudioInit: RxRing @ 0x689b60, RxRingSize: 2560
18:42:14 AudioInit: Internal sampling rate conversion for CM108 enabled
18:42:14 AudioInit: set CosPollRate to 50
18:42:14 AudioInit#2226: opening "/dev/dsp1"
18:42:14 AudioInit: Asked for a sampling rate of 48000, got 48000
18:42:14 AudioInit: sampling rate conversion from 48000 to 8000 enabled
18:42:14 Fragsize: 256, fragstotal: 5, bytes: 1280
18:42:14 EndPointInit: Setup repeat path on port OH6RUW-Kokkola.
Port OH6RUW-Kokkola: unkey
18:42:14 EndPointInit: returning 0
18:42:18 tlbcmd: "link" (0).

Program received signal SIGSEGV, Segmentation fault.
CmdLine_Handler (pClient=0x681460) at conference.c:2557
2557	         cp = strdup(&p->Buf[sizeof(NDATA)]);
(gdb) bt
#0  CmdLine_Handler (pClient=0x681460) at conference.c:2557
#1  0x00000000004319c5 in CallCurrentState (pClient=0x681460) at main.c:684
#2  0x000000000043213c in MainLoop () at main.c:508
#3  0x000000000042c2b6 in StartRunning () at thebridge.c:522
#4  0x0000000000403370 in main (argc=4, argv=0x7fffffffe658, envp=<optimized out>) at thebridge.c:381
(gdb) 
```

Added tlb.conf with .txt end for github compiance

[tlb.conf.txt](https://github.com/skiphansen/thelinkbox/files/1670260/tlb.conf.txt)

**Comment by skiphansen** [comment]
Wow, that was fast!  Do I assume correctly that this has been an issue for some time and not a regression?  The change I just made to fix the compile issue shouldn't have caused this.

**Comment by OH1KK** [comment]
This is not a regression. I got same segfault result no matter do I use thelinkbox-0.55.tgz from yahoo downlods, or precompiled debian packgage from http://www.pakettiradio.net/downloads/thelinkbox/thelinkbox_0.47-1_amd64.deb.

**Comment by skiphansen** [comment]
I have a CM108 dongle *somewhere* in my garage.  If I can find it I'll take a look.
